### ISSUE TITLE
script running issue

### ISSUE THREAD

**Issue by ghlilou97** [KennaSecurity/All_Samples#188]
Traceback (most recent call last):
	2: from csv_extract_with_details.rb:172:in `<main>'
	1: from csv_extract_with_details.rb:160:in `get_bulk_assets'
csv_extract_with_details.rb:160:in `delete': no implicit conversion of nil into String (TypeError)

**Comment by ghlilou97** [comment]
# Logfile created on 2023-05-10 12:24:52 +0200 by logger.rb/v1.4.2
E, [2023-05-10T12:26:08.980972 #21998] ERROR -- : General RestClient error... 401 Unauthorized(time: 2023-05-10 12:26:08 +0200, start time: )

**Comment by ghlilou97** [comment]
need to use '' : 'API_KEY'
